# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YihC22yQ_4bcS7OSuNbLeV3YYbSciQ4V
"""

age = input("Are you a cigarette addict older than 75 years old?").title()
chronic = input("Do you have a severe chronic disease?").title()
immune = input("Is your immune system too weak?").title()
if age == "Yes" and chronic == "Yes" and immune == "Yes":
    print("You are in risky group")
else:
    print("You are not in risky group")