# -*- coding: utf-8 -*-
"""Fibonacci_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17S6140FBixDPWe7DJi9xIh9VozwZ2e4l
"""

a = int(input("enter finish number"))
b = list(range(a+1))
fibonacci = []
for i in b:
    if len(fibonacci) == 0:
        fibonacci.append(i)
        continue
    if len(fibonacci) == 1:
        fibonacci.append(i)
        continue
    if len(fibonacci)>= 2:
          c = fibonacci[-1] + fibonacci[-2]  
          fibonacci.append(c)
          if c >= 55:
              fibonacci.pop(0)
              break
print(a)
print(b)
print(c)
print(fibonacci)

fibonacci = []
for i in range(56):
    if len(fibonacci) == 0:
        fibonacci.append(i)
        fibonacci.append(i)
        continue
    if len(fibonacci)>= 2:
        c = fibonacci[-1] + fibonacci[-2]  
        fibonacci.append(c)
        if c >= 55:
            break

print(fibonacci)

fibonacci = []
for i in range(1, 56):
    if i == 1 or i == 2:
        fibonacci.append(1)        
    elif i > 2:
        c = fibonacci[-1] + fibonacci[-2]  
        fibonacci.append(c)
        if c >= 55:
            break
print(fibonacci)

fibonacci = []
for i in range(1, 56):
    c = int(i) + (int(i) + 1)
    fibonacci.append(i)
      i += c
print(fibonacci)



fibonacci = []
listnew = list(range(-2,56))
for i in listnew:  
    if i in listnew:
      fibonacci.append((i-1)+(i-2))
print(fibonacci)

fibonacci = []
listnew = list(range(1, 56))
for i in listnew:
    c = int(i) + (int(i)+1)
    fibonacci.append(c)
    i = fibonacci[-1]
print(fibonacci)

x = [1,1]
for i in range(2, 10):  
    x.append(x[-1] + x[-2]) 
    for y in x:
        print(', '.join(str(y)))