# -*- coding: utf-8 -*-
"""letters_count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1etlEJ9QS9M_YbmjD6AlXGs9cToqzKndz
"""

a = input("enter a statement: ")
b = list(a)
d = dict()

for i in b:
  c = b.count(i)
  d.update({i:c})

print(d)