# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izumwTLOe5h_zwlEN7v3U03gxf-1ePLr
"""

name1 = "Joseph"
name2 = input("Please enter your name").title()
if name2 == name1:
    print("Hello, {}! The password is : W@12".format(name2))
else:
    print("Hello, {}! See you later.".format(name2))