# -*- coding: utf-8 -*-
"""prime_number_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VDATxoTFqk4U0hFu18CDCRPDhoZjoUI1
"""

count = 0
n = int(input("Please enter your number: "))
for i in range(2, n):
    if n % i == 0:
      count += 1
      
if n == 1:
    print(n, "is not prime number")
elif count == 0:
    print(n, "is  prime number")      
else:
     print(n, "is not prime number")