# -*- coding: utf-8 -*-
"""Prime_numbers_assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xqOZQzN2rgldIHWOjGa8LHFPN46GSA_C
"""

number = int(input("Give number : "))
list_a = set([])
for i in range(1,number + 1):
    for k in range(1,number + 1):
        if i%k == 0 and  i !=1 and  k !=1:
            list_a.add(k)
            break
list_a = list(list_a)
print(sorted(list_a))

